In [2]:
import numpy as np

# Create an Array using Numpy

#### Type cast list to array

In [4]:
#type cast list to array
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

#### typecasting 2D Array

In [5]:
nested_list = [[1,2],[3,4],[5,6]]
nested_list
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### using np.arange

np.arange function creates the array with 2 Parameters

*Start - Start of the value

*Stop - end value doesnt include it 

*Step - incremental incase if any

In [6]:
np.arange(0,10)  #Start and stop value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,100,5) #Start and stop with step value

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

#### Creating matrices/arrays with either Zeros or ones

By default numpy arrays are created as floating point arrays but can be converted to integer using dtype argument

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((4,10),dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((4,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Create an array with equidistant values between two numbers

Numpy function linspace helps in creating a array of equidistant numbers between two values.
It  includes both the start and end ranges

In [12]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Create an identity matrix

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Create array with random variables

##### rand() 
Creates an array with random variables of an Uniform distribution between 0 and 1 

In [14]:
np.random.rand(3)

array([0.42954939, 0.64387042, 0.57968108])

In [15]:
np.random.rand(3,4)

array([[0.35886495, 0.80812677, 0.22960663, 0.63836924],
       [0.72976076, 0.17750824, 0.251886  , 0.65541028],
       [0.81180988, 0.27745211, 0.59825096, 0.97648309]])

##### randn()
Creates an array with random variables of an Normal  distribution between 0 and 1 .

Has Mean = 0 and var = 1 , mean =0 indicates negative values

In [16]:
arr = np.random.randn(5)
arr

array([-0.12203585, -0.70000532, -0.62198696, -2.9494162 ,  0.53711652])

In [17]:
np.random.randn(3,4)

array([[ 0.26144898,  0.64965964, -1.79451894, -1.15762039],
       [ 0.09530447, -0.05385672, -0.61991437, -0.02648803],
       [-0.07962904,  0.69111694, -0.79150083,  0.515647  ]])

#### randint - generate a random init excluding the value given

In [18]:
for i in range (1,100):
    print(np.random.randint(5))

2
4
3
3
4
0
2
3
0
3
4
4
0
3
1
2
2
1
0
0
1
2
4
0
0
0
1
2
1
1
3
3
4
3
1
2
4
2
1
4
4
1
0
4
1
1
0
4
4
1
1
2
4
2
1
2
4
4
2
0
2
4
4
3
3
4
4
2
1
0
3
0
4
0
1
4
3
0
1
1
0
1
1
3
2
0
3
4
3
4
3
4
4
0
3
3
1
2
1


In [19]:
np.random.randint(1,100) # Provide a random number within the given range excluding the high value

81

In [20]:
np.random.randint(1,20,5) # provide the frequency of numbers given excluding the high value

array([11, 10, 15, 17,  2])

##### Sometimes we need to provide the same random numbers which we did for training for that we use a functionality called seed which has a cardinal value as input if you provide the same input value in any system it provides the same set of random number generated across different machines.

In [21]:
np.random.seed(24)
np.random.randint(1,50,(100,100))

array([[35,  4,  1, ..., 12, 32, 13],
       [22, 43, 13, ..., 28, 29, 34],
       [ 2,  3, 12, ..., 40, 12, 43],
       ...,
       [ 4, 14, 20, ..., 35, 38, 33],
       [34, 44,  7, ..., 34, 17, 27],
       [45,  2, 36, ..., 10,  3, 16]])

In [22]:
np.random.seed(24)
np.random.randint(1,10,4)

array([3, 4, 1, 8])

In [23]:
np.random.randint(1,10,4)

array([2, 2, 2, 5])

In [24]:
arr = np.random.randint(1,50,5)

In [25]:
arr

array([16,  5, 48, 36, 19])

In [26]:
arr.shape

(5,)

In [27]:
arr.reshape(5,1)

array([[16],
       [ 5],
       [48],
       [36],
       [19]])

### Min,Max arguments
min - minimum in an array
max - maximum of an array
argmax - index of the max value of the array
argmin - index of the min value of the arry

In [28]:
arr.max(),arr.argmax()

(48, 2)

In [29]:
arr.min(),arr.argmin()

(5, 1)

In [30]:
arr.dtype #provide the data type of the array


dtype('int32')

## Indexing and Slicing

In [46]:
arr_ind = np.arange(1,11)

In [47]:
arr_ind

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr_ind[5] # prints the value at index 5, index starting from 0

6

In [34]:
arr_ind[:4] # prints till the index value of 3 i.e 4 values

array([1, 2, 3, 4])

In [35]:
arr_ind[0:4] # similar to previous one

array([1, 2, 3, 4])

In [36]:
arr_ind[5:] # prints array after the 5th value i.e index 4

array([ 6,  7,  8,  9, 10])

In [37]:
arr_ind[:4] = 5 

arr_ind   # updates the value of the array till index 4 with

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

##### Slicing

Slicing creates a subset array of the pointers and not a separate array. Any changes to the subset changes are made to the original array.

In [50]:
slice_arr = arr_ind[:4]

In [51]:
slice_arr

array([1, 2, 3, 4])

In [52]:
slice_arr[:2] = 100

In [53]:
slice_arr,arr_ind

(array([100, 100,   3,   4]),
 array([100, 100,   3,   4,   5,   6,   7,   8,   9,  10]))

To avoid the above issue we need to make a copy of the existing array and then make the changes.

In [48]:
arr_new = arr_ind.copy()

In [49]:
arr_new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### indexing and slicing in 2d Array

In [56]:
arr_2d = np.random.randint(5,50,(5,5))

In [57]:
arr_2d

array([[16, 40, 20, 44, 14],
       [23, 12, 30, 40, 36],
       [33,  5, 17, 36, 38],
       [ 6, 11, 38, 22, 11],
       [ 6, 30, 15, 40,  5]])

In [61]:
arr_2d.shape

(5, 5)

In [58]:
arr_2d[3] # 2d array one index value returns the row

array([ 6, 11, 38, 22, 11])

In [60]:
arr_2d[3][4] # two index return the value at 3rd row and 4th column. indexes starts from 0

11

indexing can also be done using : as below

In [62]:
arr_2d[:2] # retrieves till first two rows (index 2 - 0,1)

array([[16, 40, 20, 44, 14],
       [23, 12, 30, 40, 36]])

In [63]:
arr_2d[2:3,2:] # retrieves the row between index 2 and 3 (row 3)  and columns from index 2 till end
# Note when 2 values are given (2:3) the lower value is included but higher value is excluded

array([[17, 36, 38]])

## Conditional Selection

###### used when we need to get a subset of the data to perform any operations and retrieve any information 

In [65]:
arr_2d > 35

array([[False,  True, False,  True, False],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [70]:
arr_new_slice = arr_2d[arr_2d > 35]

In [67]:
bool_arr = arr_2d > 35

In [68]:
bool_arr

array([[False,  True, False,  True, False],
       [False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [69]:
arr_2d [bool_arr]

array([40, 44, 40, 36, 36, 38, 38, 40])

In [72]:
arr_new_slice[:] = 30

In [73]:
arr_new_slice

array([30, 30, 30, 30, 30, 30, 30, 30])

In [74]:
arr_2d

array([[16, 40, 20, 44, 14],
       [23, 12, 30, 40, 36],
       [33,  5, 17, 36, 38],
       [ 6, 11, 38, 22, 11],
       [ 6, 30, 15, 40,  5]])

Above example shows slicing in 2d doesnt point to the pointers but creates a subset

### *Numpy Operations*

In [75]:
arr_ops = np.arange(0,10)

In [76]:
arr_ops

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr_ops.mean()

4.5

In [78]:
arr_ops + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
arr_ops/0 # divisible by zero is shown as warning and also denoted by inf --> infinity

C:\Users\karti\AppData\Local\Temp\ipykernel_8644\699198590.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_ops/0
C:\Users\karti\AppData\Local\Temp\ipykernel_8644\699198590.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr_ops/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [80]:
1/arr_ops

C:\Users\karti\AppData\Local\Temp\ipykernel_8644\3131116231.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr_ops


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [81]:
arr_ops_2d = np.arange(0,20).reshape(4,5)

In [82]:
arr_ops_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [83]:
arr_ops_2d * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [84]:
arr_ops_2d * arr_ops_2d

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [89]:
arr_ops_2d ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]], dtype=int32)

In [90]:
arr_ops_2d.sum()

190

In [91]:
arr_ops_2d.sum(axis = 0) # sum of values in every row in each column 
# 0+5+10+15,1+6+11+16,

array([30, 34, 38, 42, 46])

In [93]:
arr_ops_2d.sum(axis = 1) # sum of values of every column in each row
#0+1+2+3+4,5+6+7+8+9,.....

array([10, 35, 60, 85])

In [3]:
a = np.random.rand(5)
b = np.random.rand(5)

print(a)
print(b)

[0.6284809  0.24378799 0.24946135 0.24583952 0.33021095]
[0.15516421 0.05073825 0.25868017 0.61160615 0.77511947]


In [4]:
c = a/b**2

In [5]:
print(c)

[26.10411651 94.69812103  3.72800932  0.65721582  0.54960944]


In [6]:
a = np.random.rand(5)
b = np.random.rand(10)
d = a+b
print(a)
print(b)
print(c)

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

In [8]:
np.random.normal(1.75,0.20,10)

array([1.73714244, 1.55308238, 1.83463852, 1.40292251, 1.75685454,
       2.44021765, 1.815923  , 1.79389339, 2.2096758 , 1.52565379])

In [ ]:
np.random.normal